name = "Sindbad"
uuid = "6686e6de-2010-4bf8-9178-b2bcc470766e"
version = "0.1.0"
authors = ["SINDBAD Contributors <sindbad@bgc-jena.mpg.de>"]

[deps]
SindbadCore = "7e5cc002-9bc1-4508-860d-3c0816be375a"
SindbadData = "772b809f-5329-4bfd-a2e9-cc4714ce84b1"
SindbadML = "eb1d8004-2d42-4eef-b369-ed0645c101e8"
SindbadMetrics = "7a8077d0-ecf5-44b0-95d4-89eadbafc35c"
SindbadOptimization = "64fff8bd-0c13-402c-aa96-b97d0bc3655c"
SindbadSetup = "2b7f2987-8a1e-48b4-8a02-cc9e7c4eeb1c"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"

[sources]
SindbadCore = {path = "./SindbadCore"}
SindbadData = {path = "./SindbadData"}
SindbadMetrics = {path = "./SindbadMetrics"}
SindbadSetup = {path = "./SindbadSetup"}
SindbadTEM = {path = "./SindbadTEM"}
SindbadML = {path = "./SindbadML"}
SindbadOptimization = {path = "./SindbadOptimization"}