name = "Sindbad"
uuid = "6686e6de-2010-4bf8-9178-b2bcc470766e"
version = "0.1.0"
authors = ["SINDBAD Contributors <sindbad@bgc-jena.mpg.de>"]

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
CMAEvolutionStrategy = "8d3b24bd-414e-49e0-94fb-163cc3a3e411"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationCMAEvolutionStrategy = "bd407f91-200f-4536-9381-e4ba712f53f8"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SindbadCore = "7e5cc002-9bc1-4508-860d-3c0816be375a"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
YAXArrayBase = "90b8fcef-0c2d-428d-9c56-5f86629e9d14"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
SindbadCore = {path = "SindbadCore"}

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolyesterForwardDiff = "98d1487c-24ca-40b6-b7ab-df2af84e126b"

[extensions]
SindbadPlotsExt = "Plots"
SindbadPolyesterForwardDiffExt = "PolyesterForwardDiff"

[compat]
AxisKeys = "0.2.17"
CMAEvolutionStrategy = "0.2.6"
CSV = "0.10.15"
ComponentArrays = "0.15.30"
ConstructionBase = "1.6.0"
DimensionalData = "0.29.25"
Distributed = "1.11.0"
FillArrays = "1.15.0"
Flux = "0.16.5"
ForwardDiff = "1.3.0"
GlobalSensitivity = "2.8.0"
JLD2 = "0.6.2"
JSON = "0.21.4"
NCDatasets = "0.14.10"
NLsolve = "4.5.1"
NetCDF = "0.12.2"
Optim = "1.13.2"
Optimisers = "0.4.6"
Optimization = "5.1.0"
OptimizationCMAEvolutionStrategy = "0.3.5"
OptimizationOptimJL = "0.4.8"
PolyesterForwardDiff = "0.1.3"
PreallocationTools = "0.4.34"
ProgressMeter = "1.11.0"
QuasiMonteCarlo = "0.3.3"
Random = "1.11.0"
StableRNGs = "1.0.4"
Statistics = "1.11.1"
ThreadPools = "2.1.1"
YAXArrayBase = "0.7.6"
YAXArrays = "0.6.1, 0.7.0"
Zarr = "0.9.5"
Zygote = "0.7.10"
