name = "Sindbad"
uuid = "6686e6de-2010-4bf8-9178-b2bcc470766e"
version = "0.1.0"
authors = ["SINDBAD Contributors <sindbad@bgc-jena.mpg.de>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
PolyesterForwardDiff = "98d1487c-24ca-40b6-b7ab-df2af84e126b"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SindbadCore = "7e5cc002-9bc1-4508-860d-3c0816be375a"
SindbadData = "772b809f-5329-4bfd-a2e9-cc4714ce84b1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
SindbadCore = {path = "./SindbadCore"}

[compat]
CSV = "0.10.15"
ComponentArrays = "0.15.30"
ConstructionBase = "1.6.0"
Distributed = "1.11.0"
FiniteDiff = "2.29.0"
FiniteDifferences = "0.12.33"
Flux = "0.16.5"
ForwardDiff = "1.3.0"
JLD2 = "0.6.2"
NLsolve = "4.5.1"
Optimisers = "0.4.6"
PolyesterForwardDiff = "0.1.3"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
ThreadPools = "2.1.1"
Zygote = "0.7.10"
