name = "SindbadExperiment"
uuid = "bbd31fc6-1b7a-43f2-b792-0273fef35116"
authors = ["SINDBAD Contributors <sindbad@bgc-jena.mpg.de>"]
version = "0.1.0"

[deps]
SindbadCore = "7e5cc002-9bc1-4508-860d-3c0816be375a"
SindbadData = "772b809f-5329-4bfd-a2e9-cc4714ce84b1"
SindbadMetrics = "7a8077d0-ecf5-44b0-95d4-89eadbafc35c"
SindbadOptimization = "64fff8bd-0c13-402c-aa96-b97d0bc3655c"
SindbadSetup = "2b7f2987-8a1e-48b4-8a02-cc9e7c4eeb1c"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"
SindbadVisuals = "49d56b06-c9ff-43e2-9c93-8639e8c3cbdc"

[sources]
SindbadCore = {path = "../SindbadCore"}
SindbadData = {path = "../SindbadData"}
SindbadMetrics = {path = "../SindbadMetrics"}
SindbadOptimization = {path = "../SindbadOptimization"}
SindbadSetup = {path = "../SindbadSetup"}
SindbadTEM = {path = "../SindbadTEM"}
SindbadVisuals = {path = "../SindbadVisuals"}
