name = "SindbadTEM"
uuid = "f6108451-10cb-42fa-b0c1-67671cf08f15"
authors = ["SINDBAD Contributors <sindbad@bgc-jena.mpg.de>"]
version = "0.1.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SindbadCore = "7e5cc002-9bc1-4508-860d-3c0816be375a"
SindbadData = "772b809f-5329-4bfd-a2e9-cc4714ce84b1"
SindbadSetup = "2b7f2987-8a1e-48b4-8a02-cc9e7c4eeb1c"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[sources]
SindbadCore = {path = "../SindbadCore"}
SindbadData = {path = "../SindbadData"}
SindbadSetup = {path = "../SindbadSetup"}