name = "SindbadOptimization"
uuid = "64fff8bd-0c13-402c-aa96-b97d0bc3655c"
authors = ["SINDBAD Contributors <sindbad@bgc-jena.mpg.de>"]
version = "0.1.0"

[deps]
CMAEvolutionStrategy = "8d3b24bd-414e-49e0-94fb-163cc3a3e411"
DistributionFits = "45214091-1ed4-4409-9bcf-fdb48a05e921"
Evolutionary = "86b6b26d-c046-49b6-aa0b-5f0f74682bd6"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
MultistartOptimization = "3933049c-43be-478e-a8bb-6e0f7fd53575"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationCMAEvolutionStrategy = "bd407f91-200f-4536-9381-e4ba712f53f8"
OptimizationGCMAES = "6f0a0517-dbc2-4a7a-8a20-99ae7f27e911"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
SindbadCore = "7e5cc002-9bc1-4508-860d-3c0816be375a"
SindbadSetup = "2b7f2987-8a1e-48b4-8a02-cc9e7c4eeb1c"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[sources]
SindbadCore = {path = "../SindbadCore"}
SindbadSetup = {path = "../SindbadSetup"}
SindbadTEM = {path = "../SindbadTEM"}

[compat]
GlobalSensitivity = "2.7.0"
OptimizationCMAEvolutionStrategy = "0.3.0"
QuasiMonteCarlo = "0.3.3"
StableRNGs = "1.0.2"
