[deps]
AbstractDifferentiation = "c29ec348-61ec-40c8-8164-b8c60e9d9f3d"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GCMAES = "4aa9d100-eb0f-11e8-15f1-25748831eb3b"
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SindbadCore = "7e5cc002-9bc1-4508-860d-3c0816be375a"
SindbadData = "772b809f-5329-4bfd-a2e9-cc4714ce84b1"
SindbadExperiment = "bbd31fc6-1b7a-43f2-b792-0273fef35116"
SindbadML = "eb1d8004-2d42-4eef-b369-ed0645c101e8"
SindbadMetrics = "7a8077d0-ecf5-44b0-95d4-89eadbafc35c"
SindbadOptimization = "64fff8bd-0c13-402c-aa96-b97d0bc3655c"
SindbadSetup = "2b7f2987-8a1e-48b4-8a02-cc9e7c4eeb1c"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"
SindbadVisuals = "49d56b06-c9ff-43e2-9c93-8639e8c3cbdc"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
SindbadCore = {path = "../../SindbadCore"}
SindbadData = {path = "../../SindbadData"}
SindbadExperiment = {path = "../../SindbadExperiment"}
SindbadML = {path = "../../SindbadML"}
SindbadMetrics = {path = "../../SindbadMetrics"}
SindbadOptimization = {path = "../../SindbadOptimization"}
SindbadSetup = {path = "../../SindbadSetup"}
SindbadTEM = {path = "../../SindbadTEM"}
SindbadVisuals = {path = "../../SindbadVisuals"}
