Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
AutoPreallocation = "e7028de2-df94-4053-9fdc-99272086b8d4"
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Flatten = "4c728ea3-d9ee-5c9a-9642-b6f7d7dc04fa"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
NestedTuples = "a734d2a7-8d68-409b-9419-626914d4061d"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
SindbadOptimization = "64fff8bd-0c13-402c-aa96-b97d0bc3655c"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Sindbad = "6686e6de-2010-4bf8-9178-b2bcc470766e"
SlurmClusterManager = "c82cd089-7bf7-41d7-976b-6b5d413cbe0a"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
YAXArrayBase = "90b8fcef-0c2d-428d-9c56-5f86629e9d14"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
