[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Sinbad = "6686e6de-2010-4bf8-9178-b2bcc470766e"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
