[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
SindbadOptimization = "64fff8bd-0c13-402c-aa96-b97d0bc3655c"
SindbadCore = "7e5cc002-9bc1-4508-860d-3c0816be375a"
