[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
SindbadOptimization = "64fff8bd-0c13-402c-aa96-b97d0bc3655c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sindbad = "6686e6de-2010-4bf8-9178-b2bcc470766e"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
YAXArrayBase = "90b8fcef-0c2d-428d-9c56-5f86629e9d14"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
