[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
SindbadOptimization = "64fff8bd-0c13-402c-aa96-b97d0bc3655c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sindbad = "6686e6de-2010-4bf8-9178-b2bcc470766e"
YAXArrayBase = "90b8fcef-0c2d-428d-9c56-5f86629e9d14"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
